### ISSUE TITLE
Dodać do knowledgebase informacje o Git.

### ISSUE THREAD

**Issue by adelura** [CodeCarrotsJS/CodeCarrotsJS.github.io#1]

**Comment by AgaBacior** [comment]
Done 
Dodałam dwa linki, które są na facebooku:
try.github.io/levels/1/challenges/1
pcottle.github.io/learnGitBranching

**Comment by adelura** [comment]
Świetnie, wygląda ok :) Tak na przyszłość: Jak z treści commita będzie `fixed #1` albo `fix #1` to ten issue zamknie się automagicznie :)
