### ISSUE TITLE
Prezentacje

### ISSUE THREAD

**Issue by AgaBacior** [CodeCarrotsJS/CodeCarrotsJS.github.io#5]
Co myślicie o tym by w Bazie Wiedzy (lub w FAQ) umieścić razem wszystkie prezentacje, jedna obok drugiej, łatwo dostępne.
Jeśli pomysł się wam podoba mogę się tym zająć. 

Kurs JavaScript - PROGRAMOWANIE W JĘZYKU JAVASCRIPT (zajęcia pierwsze) http://codecarrotsjs.github.io/prezentacja-pierwsza

Kurs JavaScript - FUNKCJE część 1 http://codecarrotsjs.github.io/prezentacja-funkcje
Kurs JavaScript - FUNKCJE część 2 http://codecarrotsjs.github.io/prezentacja-funkcje-2

Kurs JavaScript - TABLICE http://codecarrotsjs.github.io/arrays

Kurs JavaScript - PĘTLE http://codecarrotsjs.github.io/loops/#/

Kurs JavaScript - DOCUMENT OBJECT MODEL http://codecarrotsjs.github.io/prezentacja-dom 

Kurs JavaScript - STRUKTURY DANYCH I PODSTAWY TERMINALA http://codecarrotsjs.github.io/prezentacja-struktury-konsola

**Comment by ghost** [comment]
Na stronie http://codecarrotsjs.github.io/schedule/ w zakładce Plan zajęć są aktualizowane informacje na temat zajęć. Prezentacje również się tam znajdują.

Niestety nie wszystkie są dodawane na bieżąco. Ostatnio zaktualizowałam zajęcia ósme. Jeżeli masz trochę czasu możesz uzupełnić pozostałe :)

**Comment by adelura** [comment]
Już jest do tego podstrona [plan zajęć](http://codecarrotsjs.github.io/schedule/), tam bym wszystko wrzucał wraz z opisem zajęć i pracą domową. To jest issue #3.

**Comment by AgaBacior** [comment]
ok
